### ISSUE TITLE
build failure with ghc 7.10

### ISSUE THREAD

**Issue by cocreature** [commercialhaskell/stack-ide#1]
After bumping filepath & text to get cabal to start building (in a clean sandbox). I ran into the following error

```
[3 of 6] Compiling IdeSession.Client.JsonAPI ( src/IdeSession/Client/JsonAPI.hs, dist/dist-sandbox-11a90ed7/build/ide-backend-client/ide-backend-client-tmp/IdeSession/Client/JsonAPI.o )

src/IdeSession/Client/JsonAPI.hs:1:1:
    Exception when trying to run compile-time code:
      Data/StackPrism/TH.hs:74:27-63: Non-exhaustive patterns in lambda

    Code: deriveStackPrismsWith prismNameForConstructor ''Maybe
```

The related [line](https://github.com/MedeaMelana/stack-prism/blob/master/Data/StackPrism/TH.hs#L74) in stackprism does indeed not catch the KindedTV case. Not sure if this is stackprism or in ide-backend-client. I don't think it's related to the bumping of filepath and text.

**Comment by chrisdone** [comment]
GHC has changed its output:

GHC 7.8.4:

``` haskell
Prelude Language.Haskell.TH> putStrLn $(reify ''Maybe >>= stringE . show)
TyConI (DataD [] Data.Maybe.Maybe [PlainTV a_1627399042] 
[NormalC Data.Maybe.Nothing [],NormalC Data.Maybe.Just [(NotStrict,VarT a_1627399042)]] 
[])
```

GHC 7.10:

``` haskell
Prelude Language.Haskell.TH> putStrLn $(reify ''Maybe >>= stringE . show)
TyConI (DataD [] GHC.Base.Maybe [KindedTV a_1627404217 StarT]
[NormalC GHC.Base.Nothing [],NormalC GHC.Base.Just [(NotStrict,VarT a_1627404217)]] 
[])
```

So stackprism needs fixing, I think. Non-exhaustive lambdas are dangerous…

**Comment by cocreature** [comment]
Thanks for the example.

**Comment by MedeaMelana** [comment]
Whoops, sorry about that. I've pushed stack-prism-0.1.3 that fixes this.
