### ISSUE TITLE
lack of license

### ISSUE THREAD

**Issue by kadoban** [commercialhaskell/stack-ide#14]
Is it an oversight that there is no license defined for this project? Based on https://www.fpcomplete.com/blog/2015/03/announce-ide-backend I had assumed that it would be Open Source, but there's no license defined in any of the .cabal files, and the LICENSE files are empty.

**Comment by chrisdone** [comment]
Yeah, we tend to choose MIT or BSD.

**Comment by mgsloan** [comment]
Added MIT license
