### ISSUE TITLE
Get dependencies before calling Ghci

### ISSUE THREAD

**Issue by NightRa** [commercialhaskell/stack-ide#20]
Stack should get all the project's dependecies before calling ghci.

**Comment by bitemyapp** [comment]
Maybe this should go to the Stack repo and not `stack-ide`?

**Comment by chrisdone** [comment]
Yeah, please move this issue to stack, @NightRa.

**Comment by mgsloan** [comment]
Yup, sounds like a report for stack - closing

**Comment by NightRa** [comment]
Yes, It got here by mistake.
