### ISSUE TITLE
Make autocompletion API more idiomatic

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack-ide#24]
This issue is tracking updating the autocompletion API to more closely match ide-backend.

From the API code:

> -- \* We try to roughly have a one-to-one mapping between the functions exported
> --   by IdeSession; for instance, ide-backend's `updateSourceFileFromFile`
> --   corresponds to the `RequestUpdateSourceFileFromFile` request and the
> --   `ResponseUpdateSourceFileFromFile` response.

However, the current autocompletion API does some smart stuff where it splits off the qualifier and filters the results in various ways.  It also only yields some portions of the info.  While this intelligence may be desirable, such logic should either be moved into ide-backend or the client.

I suspect that one of the reasons for it only yielding some of the info is to reduce the overall size of the response.  Yielding the full list of autocompletions could indeed be quite a lot of info, but I think #23 will address this well.

On the other hand, it might be a good idea for `stack-ide` to have some command variants that add some smarts and convenience.  This will save the redundancy of implementing such smarts in all the clients.  It does seem like a good idea to at least expose the more direct wrapping of ide-backend, though.

@lukexi Looks like you've got support for the current autocompletion api in your sublime plugin.  Cool!  Thoughts on changing the API like this?  Maybe it'd be good to have both `RequestGetAutoCompletion` and `RequestGetAutoCompletionSmart`?

**Comment by mgsloan** [comment]
Here's what the change looks like: https://github.com/commercialhaskell/stack-ide/commit/757f90c1777101b8c1e37a9f165b8f43c639e46a

**Comment by lukexi** [comment]
Hi Michael! Yep, that makes sense to me — definitely would be awesome to standardize as much behavior in ide-backend as possible so users can have a consistent experience everywhere they use it.

Sublime also recently added an API for displaying HTML tooltips that should offer a lot of fun uses for richer autocomplete and other query info.

(and I'm sure you already know it, but just to say it somewhere: please feel encouraged to go nuts changing the APIs as much as you like;
I built the plugin expecting tons of flux and I'm ready to keep up : ))

**Comment by mgsloan** [comment]
Cool, glad you're prepared for some flux :D

I think we'll need to consider what the policy should be for such extra processing.  This isn't the only example - my annotated type info / expression info stuff is also a circumstance where stack-ide isn't a transparent wrapper around ide-backend.  That's a good example of the pattern where you supply both the direct request and one that's got a little bit of extra processing.

**Comment by mgsloan** [comment]
Done!
