### ISSUE TITLE
Refine protocol serialization

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack-ide#27]
I figure now is a good time to revisit the current protocol serialization, as stack-mode hasn't yet been updated to the one based on Aeson TH.  The old protocol looked quite nice, but it used JsonGrammar.  JsonGrammar is very cool, but not very battle hardened and tricky to get started with.  By using Aeson TH we can avoid a lot of boilerplate.

We can get something closer to the old protocol by doing stuff like this, and adding record fields:

``` haskell
$(deriveJSON (defaultOptions
  { constructorTagModifier = fromMaybe (error "Expected Request prefix") . stripPrefix "Request"
  , sumEncoding = TaggedObject { tagFieldName = "request", contentsFieldName = "contents" }
  }) ''Request)
```

If we actually do this, then this particular naming pattern could be turned into a new TH function, so that we don't need a bunch of boilerplate.

Another part of this work on refining the serialization would be to add records labels.

**Comment by chrisdone** [comment]
This seems practically the same as the current invocation of derving JSON in the format of the fields. How does it differ?

**Comment by mgsloan** [comment]
Merely shorter constructor names, because it eliminates the common prefix.  I've considered it a bit further, though, and the default aeson encoding is decent enough.  I think record fields are probably still worthwhile, though.

**Comment by chrisdone** [comment]
I vote to leave the protocol format as it is and concentrate effort on having a mode that works reliably, until that point we have two birds in the bush and yet more time delaying this ever happening.

**Comment by mgsloan** [comment]
Agreed!
