### ISSUE TITLE
Doesn't build on windows

### ISSUE THREAD

**Issue by djrenren** [commercialhaskell/stack-ide#30]
Looks like there's a dependency on the `unix` package somewhere. This causes the build to fail on Windows. Seeing as Stack supports windows it makes sense that stack-ide should as well.

Build log: http://pastebin.com/mfhxgZNq

**Comment by cocreature** [comment]
Probably related to fpco/ide-backend#279

**Comment by djrenren** [comment]
Oh gotcha. Makes sense. Sorry for double reporting

**Comment by mgsloan** [comment]
It's all good!  Everything in stack-ide will work on windows once ide-backend supports windows.
