### ISSUE TITLE
Improve error reporting

### ISSUE THREAD

**Issue by lukexi** [commercialhaskell/stack-ide#34]
As seen in #31, stack-ide fails to report configuration errors at startup, and instead responds with

```
{"tag":"ResponseWelcome","contents":[0,1,0]}
{"tag":"ResponseUpdateSession","contents":null}
```

(without compiling anything)

A call to "RequestGetSourceErrors" works to trigger an actual helpful error, e.g.:
`
{"tag":"RequestGetSourceErrors","contents":[]}
{"tag":"ResponseGetSourceErrors","contents":[{"errorSpan":{"tag":"TextSpan","contents":"<<server died>>"},"errorKind":"KindServerDied","errorMsg":"/Users/lukexi/.stack/snapshots/x86_64-osx/lts-2.17/7.8.4/pkgdb/package.cache: GHC.PackageDb.readPackageDb: inappropriate type (not a ghc-pkg db file, wrong file magic number)"}]}
`

It would be great to find a way to trigger the error immediately on startup.

(I'll create a separate issue on `ide-backend` for the particular error in the example, which can be solved by making sure the project is using the same snapshot that ide-backend was built against — do we need a separate version of `ide-backend-server` for each package db?)

**Comment by mgsloan** [comment]
I recently created an `ide-backend` issue that ought to cover this - does it? https://github.com/fpco/ide-backend/issues/292

> do we need a separate version of ide-backend-server for each package db?

I think we'd just need a separate version of ide-backend-server for each ghc version

**Comment by mgsloan** [comment]
I've added more detailed progress reporting for recompilation, including better reporting of failure cases and server restarts: https://github.com/fpco/ide-backend/commit/702082d7d9a82deb60cbc11af9c679b5cc661b86

I've also added logging, and plumbed it through stack-ide as `ResponseLog` messages: https://github.com/fpco/ide-backend/commit/0c61a1f532907b1c7b472bc9d5eaaeec8b7a2dd9   7c816753429a97355b97277acd3d7dce24b5d025

Finally, I removed `KindServerDied`, which doesn't seem like the right way to solve this: https://github.com/fpco/ide-backend/commit/b7e54607c5b797edd155ca3d51b8e2f58244514e

Do these changes address the problem adequately?

**Comment by lukexi** [comment]
Hi Michael,
Yep, that's looking awesome. I can send the logs to the Sublime console and that'll be super helpful for debugging failures. It also reports startup failure right away as I hoped : ). Thanks a bunch!
