### ISSUE TITLE
Aux.hs is an illegal filename on Windows

### ISSUE THREAD

**Issue by garethrowlands** [commercialhaskell/stack-ide#38]
Sadly, Aux.hs is an illegal filename on Windows. Please could you rename this file so Windows users can check out the source? This limitation is a hang over from the days of DOS (AUX:) but it still applies even to modern Windows.

Steps to reproduce:
1. Get a command prompt on Windows (any version but I used Windows 8.1).
2. git clone ...
3. Checkout fails with error about Aux.hs. :-(

Workaround is easy: just call Aux.h's something else (but not Con.hs or any of the words listed here: http://blog.onetechnical.com/2006/11/16/forbidden-file-and-folder-names-on-windows/).

**Comment by garethrowlands** [comment]
I was able to get Aux.h's onto my disk (using UNC syntax, \.\...) but suspect ghc won't be able to write Aux.hi or Aux.o. I guess I'm the first person to try stack-ide on Windows?

**Comment by garethrowlands** [comment]
Ah. It depends on ide-backend-common, which depends on Unix. So I guess Windows support is right out. Where's the right place to report this? I couldn't find an ide-backend-common repo.

**Comment by CRogers** [comment]
`ide-backend-common` lives in [fpco/ide-backend](https://github.com/fpco/ide-backend).

**Comment by lukexi** [comment]
Windows support is underway! 
https://github.com/fpco/ide-backend/issues/279
I'm super keen on it too, as I've been forced into Windows by VR work : )

**Comment by mgsloan** [comment]
Wow, that's pretty terrible, I didn't know about that filename restriction on windows.  I've pushed a fix.
