### ISSUE TITLE
Optional sequence codes in request/responses 

### ISSUE THREAD

**Issue by jcpetruzza** [commercialhaskell/stack-ide#39]
I was thinking it could be quite handy for clients if they could add a sequence code in their requests (with no meaning whatsoever for `stack-ide`) and have the code quoted back in the corresponding response. A possible interaction would look like:

```
{'tag': 'RequestGetExpTypes', seq: 42, 'contents': {...}}
{'tag': 'RequestGetExpTypes', seq: 78, 'contents': {...}}
{'tag': 'ResponseGetExpTypes', seq: 42, 'contents': [....]}
{'tag': 'ResponseGetExpTypes', seq: 78, 'contents': [....]}
```

For `stack-ide` this would be of course completely straightforward to implement. Clients, on the other hand, often want to generate requests asynchronously, triggered by concurrent events (e.g. when a file is saved, when the cursor is moved, when a hotkey is pressed) and may want to process each response differently. Using this mechanism, they could just associate a different response handler to each `seq` code and have a mostly stateless main loop, instead of having to keep track of the order of requests, the pending responses, etc...

I can probably implement this feature, but just wanted to check if it's worth it first. Perhaps all this can already be handled in some other way?

**Comment by jcpetruzza** [comment]
I wanted to play with this so I just implemented it... One thing that was perhaps not clear in the proposal is that the value of the `seq` field can be just any JSON object. In my case I want to use it to encode the name and arguments of the function to call when the response arrives, so I get a sort of continuation.

**Comment by mgsloan** [comment]
Merged your PR, good idea!
