### ISSUE TITLE
Detecting newly created modules in a project

### ISSUE THREAD

**Issue by lukexi** [commercialhaskell/stack-ide#51]
Stack-IDE currently complains 
`Could not find module ‘MyModule’`
if I create a new module in an already-loaded project, add it to `other-modules` in the cabal file and try to `import` it. Is there a way to get it to pick it up (beyond restarting, which I'm currently doing manually to work around)?

**Comment by chrisdone** [comment]
I was thinking of adding this to the load command. When doing update targets, the IDE could send along with it the current file it wants to load, and if that's not in the set of targets, add it.

**Comment by chrisdone** [comment]
This command is now added as `stack ide load-targets <package-name>`. This can be used to initially figure out the modules to load, and to update to modules newly added to the Cabal file.
