### ISSUE TITLE
stack-mode only knows how to load a hardcoded buffer path

### ISSUE THREAD

**Issue by thomasjm** [commercialhaskell/stack-ide#58]
I noticed that `stack-mode` actually tries to load a hardcoded file every time it calls `stack-mode-load-buffer`? See https://github.com/commercialhaskell/stack-ide/blob/master/stack-mode/stack-mode.el#L577. I'm guessing stack-mode has only been used on a single project so far? It would be awesome if it would actually load the code for the buffer I have open :). Sorry if I'm missing something obvious here...

**Comment by mgsloan** [comment]
Hey!  That function isn't actually used for anything currently.  I've commented it out.  Use `stack-mode-reload` instead.
