### ISSUE TITLE
Prepare stack-mode for melpa

### ISSUE THREAD

**Issue by lukehoersten** [commercialhaskell/stack-ide#68]
From [melpa discussion](https://github.com/milkypostman/melpa/pull/3136#issuecomment-141000646)
- The line-wrapped description line is invalid
- None of its many package dependencies are declared (cl-lib, flycheck, haskell-mode)
- There are no `;;;###autoload` cookies
- There's no trailing comment line
- There's a spurious "checklist.el" in the directory which is apparently unused
- There's a "fifo.el" which should either be a separate package (if it's widely usable) or renamed to "stack-fifo.el" or similar
- There's no `Commentary` section, `Keywords` or other metadata headers

The melpa maintainer also mentioned that "renaming it [stack-mode], then "stack-ide" would be better than "stack-ide-mode", because the "-mode" prefix is deprecated for minor modes." Basically "stack-mode" implies a major mode for using stack.

**Comment by LukeHoersten** [comment]
Great work. Thanks a lot!

**Comment by lukehoersten** [comment]
All done. Rename will not happen at this time.
