### ISSUE TITLE
stack-mode process errors need to go to the message buffer

### ISSUE THREAD

**Issue by lukehoersten** [commercialhaskell/stack-ide#75]
Right now if there's a problem with the `stack-ide` process, `stack-mode` just fails silently instead of writing the errors somewhere.

**Comment by chrisdone** [comment]
Errors are written to `*stack:yourprojectname*`. What kind of errors are you missing?

**Comment by lukehoersten** [comment]
`stack ide` was failing to start and I guess we expected to see something in the mini buffer or `*Messages*`. I can't remember what was in the `*stack:project*` buffer at the time but I wouldn't be surprised if the errors were in there.

**Comment by lukehoersten** [comment]
I'll re-open this with more specific cases/messages if I can find what originally caused me to write the issue.
