### ISSUE TITLE
stack-mode insert type has a type error

### ISSUE THREAD

**Issue by lukehoersten** [commercialhaskell/stack-ide#76]
When running `stack-mode-type` with a non-zero argument, a type error occurs:

```
insert: Wrong type argument: char-or-string-p, nil
```

**Comment by wraithm** [comment]
+1 I get exactly the same thing.

**Comment by lukehoersten** [comment]
I think I've figured some hints out here. This is happening when an empty string is returned on the JSON API from `stack-ide` process. So that's a problem with `stack-ide` but `stack-mode` should probably do something more elegant with the empty return than having a runtime type error.

**Comment by lukehoersten** [comment]
We may actually need a special case of insert type for top level functions. Right now it wraps the expression in (name ::) when really that doesn't work for top levels.

**Comment by chrisdone** [comment]
The response from stack-ide changed format.
