### ISSUE TITLE
Flycheck errors are being reported in all buffers

### ISSUE THREAD

**Issue by lukehoersten** [commercialhaskell/stack-ide#77]
When one file has a flycheck error, the location and underline is applied to all buffers erroneously.

**Comment by chrisdone** [comment]
stack-ide checks all files when you change one file at present. This is probably why flycheck is getting all errors in every edit. I'm currently tying up a change that will make checks happen only per-module requested to be checked. This will make it substantially faster and avoid this problem.

**Comment by lukehoersten** [comment]
Sounds good.

To provide a bit more color, If buffer1 has an error at 24,10 and I switch to buffer2, the Flycheck underline will show in buffer2 at 24,10 even though there's no error there. Seems like a buffer-local is missing somewhere. This happened in the old haskell-flycheck.el as well.

**Comment by lukehoersten** [comment]
Yeah this seems fixed. Thanks.
