### ISSUE TITLE
Getting type and info of operator functions doesn't work

### ISSUE THREAD

**Issue by lukehoersten** [commercialhaskell/stack-ide#79]
Getting the type or info of functions like `<$>` and `<.>` results in nothing being returned from the JSON API.

Also, when nothing is returned in the JSON API, the type error is printed in the mini and messages buffer:

```
progn: Wrong type argument: integer-or-marker-p, nil
```

**Comment by chrisdone** [comment]
Yeah, at some point someone broke `haskell-ident-pos-at-point` on operators. Going to have to work around it.
