### ISSUE TITLE
Provide an example on how to use the application

### ISSUE THREAD

**Issue by arybczak** [commercialhaskell/stack-ide#8]
Hey,

I installed ide-backend-client, ide-backend and ide-backend-server, but when I try to run ide-backend-client from its root git repository, I get this:

```
unknown@localhost ide-backend-client $ ./ide-backend-client cabal .
{"response":"welcome","version":{"minor":1,"major":0,"patch":0}}
ide-backend-client: internal error: there is no configuration data for component CLibName
```

**Comment by chrisdone** [comment]
I don't know what that error is, I'll get back to you tomorrow.

**Comment by arybczak** [comment]
FYI, empty session starts fine, it's just the cabal one that fails.

**Comment by tobiasgwaaler** [comment]
Yes, I have the same issue. By building an image from the following Dockerfile you can reproduce it:

```
FROM haskell:7.10

RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/chrisdone/ide-backend-client.git

RUN cabal update
RUN cd ide-backend-client && cabal install
RUN cabal install ide-backend ide-backend-server ide-backend-rts

ENTRYPOINT ["/bin/bash"]
```

inside the container you can run `./ide-backend-client/dist/build/ide-backend-client/ide-backend-client cabal /ide-backend-client/` to start ide-backend-client (with itself as the target)

**Comment by tobiasgwaaler** [comment]
If the cabal version is relevant, this is the output from `cabal --version`

```
cabal-install version 1.22.2.0
using version 1.22.2.0 of the Cabal library
```

**Comment by Codas** [comment]
for the cabal command, the target command line option is more or less mandatory at the moment.

```
ide-backend-client cabal --target ide-backend-client .
```

should do the trick.

**Comment by tobiasgwaaler** [comment]
Thanks, @Codas, that worked

**Comment by lukexi** [comment]
@arybczak are you still having this issue with stack-ide (with the instructions in the README) or is it safe to close this?

**Comment by arybczak** [comment]
Explicitly providing the target indeed does solve the problem, thanks!
