### ISSUE TITLE
Should stack-mode disable default flycheckers?

### ISSUE THREAD

**Issue by lukehoersten** [commercialhaskell/stack-ide#84]
I use this in my mode hook to disable the default flycheckers which are redundant and interfere with the stack-ide flycheckers. Should we perhaps bake this logic into `stack-mode` a bit more?

``` lisp
   (flycheck-mode t)
   (flycheck-disable-checker 'haskell-ghc)
   (flycheck-disable-checker 'haskell-stack-ghc)
   (flycheck-clear t)
   (stack-mode t)
```

**Comment by cocreature** [comment]
Imho this should maybe be added to the documentation but I don't like the idea of messing with the configuration the user has set.

**Comment by lukehoersten** [comment]
Agreed. I'll add it to the docs.

**Comment by lukehoersten** [comment]
Deprecated
